apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      enableServiceLinks: false
      containers:
        - name: redis
          image: redis:6.2.6
          imagePullPolicy: Always
          ports:
            - name: redis
              containerPort: 6379